### PR TITLE
Update README.md to be more accurate

### PR DESCRIPTION
**Pull request by vardenixxxas**
based

### CODE REVIEW

**Review by DataM0del — APPROVED** [review]
Don't forget to delete `D:\` and all other disk things

**Comment by vardenixxxas** [comment]
> Don't forget to delete `D:\` and all other disk things

great idea

**Comment by vardenixxxas** [comment]
@DataM0del i updated the PR

**Review by DataM0del — APPROVED** [review]
Don't forget A and B!

**Comment by vardenixxxas** [comment]
> Don't forget A and B!

bro nobody uses floppy drives anymore

**Comment by DataM0del** [comment]
> > Don't forget A and B!
> 
> bro nobody uses floppy drives anymore

you can still assign A and B to other drives

**Pull request closed without merging**
